"""add retrieval metadata columns

Revision ID: b332d2e1fdd0
Revises: 
Create Date: 2026-05-06 17:54:09.350733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b332d2e1fdd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('document_chunks', sa.Column('source_url', sa.String(), nullable=True))
    op.alter_column('document_chunks', 'document_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'document_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('document_chunks', 'source_url')
    op.drop_column('document_chunks', 'source_type')
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###
